import { PRODUCT_TYPES, calculateProduct, allocateWithdrawal, finiteNonNegative } from './calculations.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clone=x=>JSON.parse(JSON.stringify(x));
const STORE='drawwise-wizard-v4'; const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
let settings=clone(PRODUCT_TYPES), screen=1;
let state=load()||{requiredNet:0,expectedInflation:2.5,annualReturn:7,years:10,products:[make()]};
function make(type='moneyFund',value=0,cost=0){return{id:uid(),type,value,cost,annualReturn:.07,years:10,cpiAdjustment:0,taxNowOverride:'',taxFutureOverride:'',wrapperOverride:'',taxBasisOverride:'',rewardsRatio:.67,severanceRatio:.33,rewardsTaxRate:.35,severanceTaxRate:0,severanceWithdrawable:false,isLiquid:true}}
function load(){try{return JSON.parse(localStorage.getItem(STORE))}catch{return null}} function save(){localStorage.setItem(STORE,JSON.stringify(state))}
const money=new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}), money2=new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',minimumFractionDigits:2,maximumFractionDigits:2});
const fmt=n=>money.format(Number.isFinite(n)?n:0), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function calculated(){return state.products.map(p=>calculateProduct({...p,expectedInflation:finiteNonNegative(state.expectedInflation)/100},settings[p.type]||PRODUCT_TYPES.other))} function result(){return allocateWithdrawal(calculated(),state.requiredNet,'planning')}
function go(n){if(n===2&&state.requiredNet<=0){toast('יש להזין סכום נטו גדול מאפס');return}screen=Math.max(1,Math.min(4,n));$$('.screen').forEach(x=>x.classList.toggle('active',+x.dataset.screen===screen));$$('.steps button').forEach((x,i)=>{x.classList.toggle('active',i+1===screen);x.classList.toggle('done',i+1<screen)});if(screen===2)renderProducts();if(screen===3)renderResults();if(screen===4)renderAdvanced();scrollTo({top:0,behavior:'smooth'})}
function typeOptions(selected){return Object.entries(settings).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${esc(v.label)}</option>`).join('')}
function renderProducts(){const root=$('#products');root.innerHTML=state.products.map((p,i)=>`<article class="product-card" data-id="${p.id}"><div class="product-head"><h3>${esc((settings[p.type]||PRODUCT_TYPES.other).label)}</h3><button data-remove aria-label="מחיקת מוצר">מחיקה</button></div><div class="product-grid"><label>סוג המוצר<select data-k="type">${typeOptions(p.type)}</select></label><label>שווי נוכחי (₪)<input data-k="value" type="number" min="0" value="${p.value}"></label><label>עלות ממוצעת / הפקדות (₪)<input data-k="cost" type="number" min="0" value="${p.cost}"></label></div></article>`).join('');root.querySelectorAll('.product-card').forEach(card=>{const p=state.products.find(x=>x.id===card.dataset.id);card.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{p[el.dataset.k]=el.dataset.k==='type'?el.value:finiteNonNegative(el.value);save();renderProducts()});card.querySelector('[data-remove]').onclick=()=>{state.products=state.products.filter(x=>x.id!==p.id);save();renderProducts()}})}
function naturalReason(r){if(r.taxNow===0)return r.wrapperCostEstimate>.01?'המשיכה פטורה, אך כדאי לשקול את אובדן הצמיחה הפטורה.':'המשיכה פטורה ממס לפי ההנחה.';if(r.gainRatio<.03)return 'רכיב הרווח קטן, ולכן המס המיידי נמוך יחסית.';if(r.taxBasis==='real'&&r.cpiAdjustment>0)return 'ההצמדה למדד מקטינה את הרווח החייב במס.';if(r.wrapperCostEstimate>.08)return 'נשמר להמשך ככל האפשר בגלל יתרון מס עתידי.';return 'עלות המס המשוערת נמוכה יחסית למוצרים שאחריו.'}
function renderResults(){const r=result(),rows=r.rows;const cards=[['נטו נדרש',fmt(r.requiredNet)],['נטו בתכנית',fmt(r.allocatedNet)],['ברוטו כולל',fmt(r.totalGross)],['מס משוער',fmt(r.totalTax)],['חוסר',fmt(r.shortfall)],['מקורות בשימוש',r.productsUsed],['סטטוס',r.shortfall<.01?'הצורך כוסה':'חסר סכום']];$('#summaryCards').innerHTML=cards.map((c,i)=>`<div class="summary-card ${i===6?'status '+(r.shortfall<.01?'ok':'bad'):''}"><small>${c[0]}</small><strong>${c[1]}</strong></div>`).join('');$('#statusMessage').innerHTML=r.shortfall>.01?`<div class="status-banner">חסרים <b>${fmt(r.shortfall)}</b> להשלמת היעד.</div>`:'';$('#resultsBody').innerHTML=rows.map(x=>`<tr class="${x.gross>.01?'active':'inactive'}"><td>${x.rank}</td><td><b>${esc(settings[x.type].label)}</b><br><small>${x.taxBasis==='real'?'מס ריאלי':x.taxBasis==='nominal'?'מס נומינלי':'פטור'}</small></td><td class="amount">${money2.format(x.value)}</td><td class="amount">${money2.format(x.gross)}</td><td class="amount">${money2.format(x.gainComponent)}</td><td class="amount">${money2.format(x.tax)}</td><td class="amount"><b>${money2.format(x.net)}</b></td><td class="amount">${money2.format(x.remainingValue)}</td><td><small>${naturalReason(x)}</small></td></tr>`).join('');$('#resultsFoot').innerHTML=`<tr><td colspan="2">סה״כ</td><td class="amount">${money2.format(rows.reduce((s,x)=>s+x.value,0))}</td><td class="amount">${money2.format(r.totalGross)}</td><td class="amount">${money2.format(rows.reduce((s,x)=>s+x.gainComponent,0))}</td><td class="amount">${money2.format(r.totalTax)}</td><td class="amount">${money2.format(r.allocatedNet)}</td><td class="amount">${money2.format(rows.reduce((s,x)=>s+x.remainingValue,0))}</td><td></td></tr>`}
function renderAdvanced(){const root=$('#advancedProducts');root.innerHTML=state.products.map(p=>{const d=settings[p.type],basis=p.taxBasisOverride||d.taxBasis||'nominal';return`<article class="advanced-card" data-id="${p.id}"><h3>${esc(d.label)}</h3><div class="advanced-grid"><label>בסיס המס<select data-k="taxBasisOverride"><option value="" ${!p.taxBasisOverride?'selected':''}>אוטומטי — ${basis==='real'?'ריאלי':basis==='exempt'?'פטור':'נומינלי'}</option><option value="real" ${p.taxBasisOverride==='real'?'selected':''}>ריאלי</option><option value="nominal" ${p.taxBasisOverride==='nominal'?'selected':''}>נומינלי</option><option value="exempt" ${p.taxBasisOverride==='exempt'?'selected':''}>פטור</option></select></label><label>הצמדה מצטברת מאז הרכישה (%)<input data-k="cpiAdjustment" type="number" min="0" step=".1" value="${p.cpiAdjustment*100}" ${basis!=='real'?'disabled':''}></label><label>תשואה שנתית צפויה (%)<input data-k="annualReturn" type="number" min="0" step=".1" value="${p.annualReturn*100}"></label><label>שנים קדימה<input data-k="years" type="number" min="0" value="${p.years}"></label><label>מס היום — override (%)<input data-k="taxNowOverride" type="number" min="0" value="${p.taxNowOverride===''?'':p.taxNowOverride*100}" placeholder="${d.taxNow*100}"></label><label>ערך דחיית מס (%)<input data-k="wrapperOverride" type="number" min="0" value="${p.wrapperOverride===''?'':p.wrapperOverride*100}" placeholder="${d.wrapperCost*100}"></label></div></article>`}).join('');root.querySelectorAll('.advanced-card').forEach(card=>{const p=state.products.find(x=>x.id===card.dataset.id);card.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{const k=el.dataset.k;p[k]=['taxBasisOverride'].includes(k)?el.value:el.value===''?'':finiteNonNegative(el.value)/(['years'].includes(k)?1:100);save();renderAdvanced()})});renderTaxSettings()}
function renderTaxSettings(){$('#taxBody').innerHTML=Object.entries(settings).map(([k,d])=>`<tr data-type="${k}"><td><b>${esc(d.label)}</b></td><td><select data-k="taxBasis"><option value="real" ${d.taxBasis==='real'?'selected':''}>ריאלי</option><option value="nominal" ${d.taxBasis==='nominal'?'selected':''}>נומינלי</option><option value="exempt" ${d.taxBasis==='exempt'?'selected':''}>פטור</option></select></td><td><input data-k="taxNow" type="number" value="${d.taxNow*100}">%</td><td><input data-k="taxFuture" type="number" value="${d.taxFuture*100}">%</td><td><input data-k="wrapperCost" type="number" value="${d.wrapperCost*100}">%</td><td><textarea data-k="assumption">${esc(d.assumption)}</textarea></td></tr>`).join('');$('#taxBody').querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{const d=settings[el.closest('tr').dataset.type],k=el.dataset.k;d[k]=['taxNow','taxFuture','wrapperCost'].includes(k)?finiteNonNegative(el.value)/100:el.value;renderAdvanced()})}
function summary(){const r=result();return`תכנית משיכה\nנטו נדרש: ${fmt(r.requiredNet)}\nברוטו: ${fmt(r.totalGross)}\nמס משוער: ${fmt(r.totalTax)}\n${r.rows.filter(x=>x.gross>.01).map(x=>`${settings[x.type].label}: נטו ${fmt(x.net)}, מס ${fmt(x.tax)}`).join('\n')}\nמודל תכנוני בלבד.`}
function exportCsv(){const r=result(),data=[['סוג','שווי','ברוטו','רווח חייב','מס','נטו','יתרה'],...r.rows.map(x=>[settings[x.type].label,x.value,x.gross,x.gainComponent,x.tax,x.net,x.remainingValue]),['סה״כ','',r.totalGross,'',r.totalTax,r.allocatedNet,'']];const csv='\uFEFF'+data.map(a=>a.map(v=>`"${v}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='withdrawal-plan.csv';a.click()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2000)}
$$('[data-next]').forEach(b=>b.onclick=()=>go(screen+1));$$('[data-back]').forEach(b=>b.onclick=()=>go(screen-1));$$('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go));$('#requiredNet').oninput=e=>{state.requiredNet=finiteNonNegative(e.target.value);$('#heroNet').textContent=fmt(state.requiredNet);save()};$('#addProductBtn').onclick=()=>{state.products.push(make());save();renderProducts()};$('#expectedInflation').oninput=e=>{state.expectedInflation=finiteNonNegative(e.target.value);save()};$('#recalcBtn').onclick=()=>go(3);$('#resetTaxBtn').onclick=()=>{if(confirm('לשחזר את כל ברירות המחדל?')){settings=clone(PRODUCT_TYPES);renderAdvanced()}};$('#printBtn').onclick=()=>print();$('#csvBtn').onclick=exportCsv;$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(summary());toast('הסיכום הועתק')}catch{const t=document.createElement('textarea');t.value=summary();document.body.append(t);t.select();document.execCommand('copy');t.remove();toast('הסיכום הועתק')}};
$('#heroNet').textContent=fmt(state.requiredNet);$('#requiredNet').value=state.requiredNet;$('#expectedInflation').value=state.expectedInflation;renderProducts();
