document.querySelector('[data-screen="3"]').id='results';
document.querySelector('#results .screen-head')?.classList.add('section-header');
document.querySelector('.secure')?.remove();
const stepLabels=['הצורך','הנתונים','התכנית'];$$('.steps button').slice(0,3).forEach((b,i)=>b.querySelector('span').textContent=stepLabels[i]);
document.querySelector('.intro h1').textContent='כמה כסף צריך?';netInput.placeholder='הכנס סכום נטו';
const orb=document.querySelector('.orb');orb.querySelector('span').textContent='סכום היעד';orb.querySelector('i').textContent='נטו';
document.querySelector('[data-screen="2"] .eyebrow').textContent='שלב 2 מתוך 3';document.querySelector('[data-screen="3"] .eyebrow').textContent='שלב 3 מתוך 3';
function replaceTerminology(root=document.body){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.matches('script,style'))continue;node.nodeValue=node.nodeValue.replaceAll('מוצרים','תכניות').replaceAll('מוצר','תכנית')}}
replaceTerminology();
const correctionProducts=renderProducts;
renderProducts=function(){correctionProducts();const root=$('#products'),p=state.products[productStep],screen2=document.querySelector('[data-screen="2"]');if(!screen2.querySelector('.step-goal-orb'))screen2.insertAdjacentHTML('afterbegin',`<div class="step-goal-orb"><small>סכום היעד</small><strong>${fmt(state.requiredNet)}</strong><small>נטו</small></div>`);else screen2.querySelector('.step-goal-orb strong').textContent=fmt(state.requiredNet);const del=root.querySelector('[data-remove]');if(del){del.innerHTML='🗑️';del.title='מחיקת תכנית';del.setAttribute('aria-label','מחיקת תכנית')};const nav=root.querySelector('.product-nav');nav.innerHTML=`<button class="outline" id="nextProduct">${productStep<state.products.length-1?'התכנית הבאה ←':'＋ הוספת תכנית'}</button><button class="outline" id="showPlanNow">הצגת תכנית המשיכה</button><button class="outline" id="prevProduct">${productStep===0?'חזור':'→ התכנית הקודמת'}</button>`;$('#nextProduct').onclick=()=>{if(productStep<state.products.length-1)productStep++;else{state.products.push(make());productStep=state.products.length-1;save()}renderProducts()};$('#showPlanNow').onclick=()=>go(3);$('#prevProduct').onclick=()=>{if(productStep===0)go(1);else{productStep--;renderProducts()}};const type=root.querySelector('[data-k="type"]');type.onchange=e=>{p.type=e.target.value;if(settings[p.type]?.noCost)p.cost=p.value;save();renderProducts();setTimeout(()=>$('#products [data-k="value"]')?.focus(),0)};replaceTerminology(root)};

function futureNetCost(x){const outsideTax=.25;return Math.max(0,x.futureGainPerShekel*Math.max(0,outsideTax-x.taxFuture))}
naturalReason=function(r){const immediate=r.taxCostPerNet*100,future=r.futureOpportunityCostPerNet||0;let text=immediate<.1?'אין מס מיידי צפוי לפי ההנחות.':`עלות המס המיידית היא כ־${immediate.toFixed(2)}% מכל שקל נטו.`;if(future>.005)text+=` בנוסף, כל 1 ₪ נטו שנמשך מוותר על שווי עתידי נטו מוערך של ${future.toFixed(2)} ₪, לפי התשואה, התקופה והמס העתידי שהוגדרו.`;else text+=' לפי ההנחות לא זוהה אובדן עתידי מהותי.';return text}
const correctionResults=renderResults;
renderResults=function(){correctionResults();const r=result(),total=state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0),zone=$('#results');if(!zone.querySelector('.priority-heading'))zone.querySelector('.section-header').insertAdjacentHTML('afterend','<div class="priority-heading"><span class="rank-icon">1</span><div><h3>סדר עדיפות מומלץ למשיכה</h3><p>שורה 1 היא התכנית שממנה מומלץ להתחיל. לאחר מיצוי הסכום הנדרש עוברים לשורה הבאה.</p></div></div>');$('#summaryCards').className='kpis';$('#summaryCards').innerHTML=`<div class="summary-card"><small>שווי נוכחי כולל</small><strong>${fmt(total)}</strong></div><div class="summary-card"><small>סכום משיכה מומלץ</small><strong>${fmt(r.totalGross)}</strong></div><div class="summary-card"><small>מס משוער</small><strong>${fmt(r.totalTax)}</strong></div><div class="summary-card net-target"><small>נטו מבוקש</small><strong>${fmt(r.requiredNet)}</strong></div><div class="summary-card shortfall ${r.shortfall>.01?'positive':'zero'}"><small>חוסר</small><strong>${fmt(r.shortfall)}</strong></div>`;const headers=$$('.result-panel thead th');if(headers[3])headers[3].textContent='סכום משיכה מומלץ';if(!headers.some(h=>h.dataset.future)){const reason=headers[headers.length-1],th=document.createElement('th');th.dataset.future='1';th.innerHTML='עלות עתידית נטו לכל 1 ₪<span class="future-help">אומדן ליתרון המס העתידי שאובד במשיכה היום</span>';reason.before(th)}const rows=r.rows;$$('#resultsBody tr').forEach((tr,i)=>{const reason=tr.lastElementChild;if(!tr.querySelector('.future-cost')){const td=document.createElement('td'),cost=futureNetCost(rows[i]);td.className='future-cost';td.innerHTML=`${cost.toFixed(2)} ₪<span class="future-help">לכל 1 ₪ שנמשך</span>`;reason.before(td)}});const foot=$('#resultsFoot tr');if(foot&&!foot.querySelector('[data-future-foot]')){const last=foot.lastElementChild,td=document.createElement('td');td.dataset.futureFoot='1';td.textContent='—';last.before(td)}replaceTerminology(zone)};

const inflation=()=>finiteNonNegative(state.expectedInflation)/100;function realReturnText(){const nominal=.07,real=(1+nominal)/(1+inflation())-1;return`בדוגמה של תשואה נומינלית 7.00% ואינפלציה ${state.expectedInflation.toFixed(2)}%, התשואה הריאלית היא ${Math.max(0,real*100).toFixed(2)}%. הנתון משפיע רק על תכניות שבהן המס מחושב על רווח ריאלי ועל אומדן העלות העתידית.`}
const correctionAdvanced=renderAdvanced;
renderAdvanced=function(){correctionAdvanced();const card=document.querySelector('.inflation-card');card.querySelector('p').textContent='האינפלציה מפחיתה את הרווח החייב במס בתכניות שממוסות על רווח ריאלי, ומשפיעה על אומדן היתרון העתידי של השארת הכסף בתכנית.';let exp=card.querySelector('.inflation-explainer');if(!exp){card.insertAdjacentHTML('beforeend',`<div class="inflation-explainer"><span class="inflation-result">${realReturnText()}</span></div>`);exp=card.querySelector('.inflation-explainer')}else exp.querySelector('.inflation-result').textContent=realReturnText();$('#expectedInflation').oninput=e=>{state.expectedInflation=finiteNonNegative(e.target.value);save();exp.querySelector('.inflation-result').textContent=realReturnText()};replaceTerminology(document.querySelector('[data-screen="4"]'))};
renderProducts();
