let productStep=0;
document.body.insertAdjacentHTML('afterbegin','<a class="skip-link" href="#mainContent">דלג לתוכן המרכזי</a>');
document.querySelector('main').id='mainContent';
document.querySelector('.brand').insertAdjacentHTML('afterbegin','<img class="client-logo" src="./assets/roei-romano-logo.png" alt="רועי רומנו, מתכנן פיננסי">');
document.querySelector('.brand>span').remove();
document.querySelector('.intro .eyebrow').textContent='מתחילים מהיעד';
document.querySelector('.intro h1').textContent='כמה כסף צריך (נטו)?';

renderProducts=function(){
  if(!state.products.length) state.products.push(make());
  productStep=Math.max(0,Math.min(productStep,state.products.length-1));
  const p=state.products[productStep],d=settings[p.type]||PRODUCT_TYPES.other,noCost=!!d.noCost,total=state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0),root=$('#products');
  root.className='products product-single';
  root.innerHTML=`<div class="product-progress"><div><span>מוצר ${productStep+1} מתוך ${state.products.length}</span><strong> · ${esc(d.label)}</strong></div><div class="current-total"><small>שווי כל המוצרים שהוזנו</small><b>${fmt(total)}</b></div></div><article class="product-card" data-id="${p.id}"><div class="product-head"><h3>${esc(d.label)}</h3>${state.products.length>1?'<button data-remove>מחיקת המוצר</button>':''}</div><div class="product-grid ${noCost?'no-cost':''}"><label>סוג המוצר<select data-k="type">${typeOptions(p.type)}</select></label><label>שווי נוכחי (₪)<input data-k="value" inputmode="decimal" type="number" min="0" value="${p.value}"></label><label>עלות ממוצעת / הפקדות (₪)<input data-k="cost" inputmode="decimal" type="number" min="0" value="${p.cost}"></label></div>${noCost?'<p class="simple-help">במוצר פנסיוני נדרש בשלב זה רק השווי הנוכחי. זמינות הכספים והמס ייבדקו במסך ההתאמות.</p>':''}</article><div class="product-nav"><button class="outline" id="prevProduct" ${productStep===0?'disabled':''}>→ המוצר הקודם</button><div class="center-actions"><button class="outline" id="showPlanNow">הצגת התכנית עכשיו</button><button class="cta" id="nextProduct">${productStep===state.products.length-1?'＋ הוספת מוצר נוסף':'המוצר הבא ←'}</button></div></div>`;
  const card=root.querySelector('.product-card');
  card.querySelector('[data-k="type"]').onchange=e=>{p.type=e.target.value;if(settings[p.type]?.noCost)p.cost=p.value;save();renderProducts()};
  card.querySelector('[data-k="value"]').oninput=e=>{p.value=finiteNonNegative(e.target.value);if(settings[p.type]?.noCost)p.cost=p.value;save();root.querySelector('.current-total b').textContent=fmt(state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0))};
  const cost=card.querySelector('[data-k="cost"]');if(cost)cost.oninput=e=>{p.cost=finiteNonNegative(e.target.value);save()};
  card.querySelector('[data-remove]')?.addEventListener('click',()=>{state.products.splice(productStep,1);productStep=Math.max(0,productStep-1);save();renderProducts()});
  $('#prevProduct').onclick=()=>{productStep--;renderProducts()};
  $('#showPlanNow').onclick=()=>go(3);
  $('#nextProduct').onclick=()=>{if(productStep<state.products.length-1){productStep++;renderProducts()}else{state.products.push(make());productStep=state.products.length-1;save();renderProducts()}};
};

const baseRenderResults=renderResults;
renderResults=function(){baseRenderResults();const total=state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0),cards=$$('#summaryCards .summary-card');if(cards[1]){cards[1].querySelector('small').textContent='שווי נוכחי כולל';cards[1].querySelector('strong').textContent=fmt(total)}const headers=$$('.result-panel thead th');if(headers[3])headers[3].textContent='סכום משיכה (ברוטו)';$('#resultsBody').querySelectorAll('tr').forEach((tr,i)=>{const row=result().rows[i];if(row?.type==='education')tr.lastElementChild?.insertAdjacentHTML('beforeend','<span class="loan-note">כדאי לשקול גם הלוואת בלון/שפיצר כנגד הקרן: הכסף נשאר מושקע, ולעיתים ניתן לקבל ריבית אטרקטיבית. יש לבדוק תנאים וסיכון.</span>')});if(!document.querySelector('.contact-card'))document.querySelector('.result-panel').insertAdjacentHTML('afterend','<div class="contact-card"><div><b>רוצים לבדוק תנאי הלוואה ולעבור יחד על התכנית?</b><p>רועי רומנו, מתכנן פיננסי</p><span class="email-consent">הנתונים ייפתחו בתוכנת הדוא״ל רק לאחר אישורכם.</span></div><button id="emailPlan">שליחת התכנית לרועי</button></div>');$('#emailPlan').onclick=()=>{if(confirm('לפתוח הודעת דוא״ל חדשה אל roeir@ar-fo.co.il עם סיכום התכנית? הנתונים יועברו רק אם תשלחו את ההודעה.'))location.href=`mailto:roeir@ar-fo.co.il?subject=${encodeURIComponent('תכנית משיכה לבדיקה')}&body=${encodeURIComponent(summary())}`}};

const baseAdvanced=renderAdvanced;
renderAdvanced=function(){baseAdvanced();$$('.advanced-card').forEach(card=>{const returnInput=card.querySelector('[data-k="annualReturn"]');if(returnInput){returnInput.step='.01';returnInput.value=Number(returnInput.value).toFixed(2)}const tax=card.querySelector('[data-k="taxNowOverride"]');if(tax)tax.closest('label').childNodes[0].textContent='שיעור מס חלופי (%)';const def=card.querySelector('[data-k="wrapperOverride"]');if(def){def.closest('label').childNodes[0].textContent='חשיבות שמירת הטבת המס (%)';def.closest('label').insertAdjacentHTML('beforeend','<small class="simple-help">אומדן להשפעה העתידית של ויתור על פטור או דחיית מס. ערך גבוה גורם למערכת לשמור את המוצר להמשך.</small>')}})};

document.body.insertAdjacentHTML('beforeend',`<button class="access-btn" aria-label="פתיחת תפריט נגישות" aria-expanded="false">♿</button><div class="access-panel" aria-label="אפשרויות נגישות"><b>התאמות נגישות</b><button data-a="large">הגדלת טקסט</button><button data-a="contrast">ניגודיות גבוהה</button><button data-a="links">הדגשת קישורים</button><button data-a="reset">איפוס התאמות</button></div><div class="modal" id="privacyModal" role="dialog" aria-modal="true" aria-labelledby="privacyTitle"><div class="modal-card"><button class="close">סגירה</button><h2 id="privacyTitle">מדיניות פרטיות</h2><p><b>בעל השליטה והתקשרות:</b> רועי רומנו, roeir@ar-fo.co.il.</p><p>המחשבון פועל מקומית בדפדפן. הנתונים הפיננסיים נשמרים ב־localStorage במכשיר לצורך המשך עבודה ואינם נשלחים לבעל האתר או לצד שלישי. אין חובה חוקית למסור מידע, ואפשר להשתמש במחשבון ללא שם או פרטים מזהים.</p><p>בלחיצה על שליחת התכנית נפתחת תוכנת הדוא״ל שלכם. רק אם תבחרו לשלוח, הפרטים יועברו לרועי רומנו לצורך מעבר על התכנית ויצירת קשר. ניתן לעיין במידע שנשלח, לבקש תיקון או מחיקה בפנייה לדוא״ל.</p><p>האתר אינו משתמש בעוגיות פרסום, ניתוח או מעקב. הוא משתמש באחסון מקומי חיוני בלבד. ניתן למחוק את הנתונים דרך הגדרות הדפדפן.</p><p>אין להזין מידע אישי רגיש שאינו דרוש לחישוב. מדיניות זו נועדה לשקף את עקרונות חוק הגנת הפרטיות ותיקון 13, אך אינה תחליף לייעוץ משפטי פרטני.</p></div></div><div class="modal" id="accessModal" role="dialog" aria-modal="true"><div class="modal-card"><button class="close">סגירה</button><h2>הצהרת נגישות</h2><p>נעשו התאמות להפעלה במקלדת, סימון פוקוס, ניגודיות, הגדלת טקסט, תוויות לשדות והתאמה למסכים שונים. היעד הוא התאמה לת״י 5568 ברמה AA.</p><p>אם נתקלתם בקושי, פנו אל רועי רומנו: roeir@ar-fo.co.il, וציינו את הפעולה שניסיתם לבצע.</p><p>הצהרה זו עודכנה באוגוסט 2026.</p></div></div>${localStorage.getItem('dw-cookie-ok')?'':'<div class="cookie-banner"><b>פרטיות ואחסון מקומי</b><p>אין באתר עוגיות מעקב. נתוני המחשבון נשמרים רק במכשיר באמצעות אחסון מקומי חיוני.</p><button>הבנתי</button></div>'}`);
document.querySelector('footer').insertAdjacentHTML('beforeend','<div class="legal-links"><button id="privacyLink">מדיניות פרטיות</button><button id="accessLink">הצהרת נגישות</button></div>');
const accessBtn=document.querySelector('.access-btn'),accessPanel=document.querySelector('.access-panel');accessBtn.onclick=()=>{accessPanel.classList.toggle('open');accessBtn.setAttribute('aria-expanded',accessPanel.classList.contains('open'))};accessPanel.onclick=e=>{const a=e.target.dataset.a;if(a==='large')document.body.classList.toggle('large-text');if(a==='contrast')document.body.classList.toggle('high-contrast');if(a==='links')document.body.classList.toggle('underline-links');if(a==='reset')document.body.classList.remove('large-text','high-contrast','underline-links')};
function openModal(id){document.querySelector(id).classList.add('open');document.querySelector(id+' .close').focus()}$('#privacyLink').onclick=()=>openModal('#privacyModal');$('#accessLink').onclick=()=>openModal('#accessModal');$$('.modal .close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));document.querySelector('.cookie-banner button')?.addEventListener('click',e=>{localStorage.setItem('dw-cookie-ok','1');e.target.closest('.cookie-banner').remove()});
renderProducts();
