const MAX_WITHDRAWAL=99000000;
const parseMoney=v=>Math.min(MAX_WITHDRAWAL,finiteNonNegative(String(v??'').replace(/[^0-9.]/g,'')));
const formatInput=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(finiteNonNegative(n));
const requiredField=$('#requiredNet');requiredField.type='text';requiredField.inputMode='numeric';requiredField.maxLength=12;requiredField.value=formatInput(state.requiredNet);requiredField.setAttribute('aria-describedby','requiredLimit');requiredField.insertAdjacentHTML('afterend','<small id="requiredLimit" class="simple-help">עד 99,000,000 ₪</small>');requiredField.oninput=e=>{const caret=e.target.selectionStart,raw=e.target.value,parsed=parseMoney(raw);state.requiredNet=parsed;e.target.value=formatInput(parsed);$('#heroNet').textContent=fmt(parsed);save()};requiredField.onblur=e=>e.target.value=formatInput(state.requiredNet);

const luxuryRenderProducts=renderProducts;
renderProducts=function(){luxuryRenderProducts();const root=$('#products'),ledger=state.products.map((x,i)=>`<div class="ledger-item"><span>${i+1}. ${esc(settings[x.type]?.label||'טרם נבחר סוג')}</span><b>${fmt(x.value)}</b></div>`).join('');root.querySelector('.product-progress').insertAdjacentHTML('afterend',`<aside class="product-ledger"><h3>המוצרים שכבר הוזנו</h3>${ledger||'<div class="ledger-empty">עדיין לא הוזנו מוצרים</div>'}</aside>`);const value=root.querySelector('[data-k="value"]'),cost=root.querySelector('[data-k="cost"]');[value,cost].filter(Boolean).forEach(input=>{const key=input.dataset.k;input.type='text';input.inputMode='numeric';input.value=formatInput(state.products[productStep][key]);input.oninput=e=>{const p=state.products[productStep],parsed=parseMoney(e.target.value);p[key]=parsed;if(key==='value'&&settings[p.type]?.noCost)p.cost=parsed;e.target.value=formatInput(parsed);save();root.querySelector('.current-total b').textContent=fmt(state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0));const item=root.querySelectorAll('.ledger-item')[productStep]?.querySelector('b');if(item)item.textContent=fmt(parsed)}})};

const luxuryAdvanced=renderAdvanced;
renderAdvanced=function(){luxuryAdvanced();$$('.advanced-card').forEach(card=>{const input=card.querySelector('[data-k="wrapperOverride"]');if(!input)return;const p=state.products.find(x=>x.id===card.dataset.id),d=settings[p.type],current=p.wrapperOverride===''?d.wrapperCost:p.wrapperOverride;const select=document.createElement('select');select.className='benefit-select';select.innerHTML=`<option value="0" ${current===0?'selected':''}>ללא חשיבות מיוחדת</option><option value="0.05" ${current>.001&&current<.1?'selected':''}>חשוב לשמור להמשך</option><option value="0.15" ${current>=.1&&current<.2?'selected':''}>חשוב מאוד לשמור</option><option value="0.25" ${current>=.2?'selected':''}>עדיפות גבוהה להשאיר</option>`;select.onchange=()=>{p.wrapperOverride=Number(select.value);save()};input.replaceWith(select);const label=select.closest('label');label.childNodes[0].textContent='כמה חשוב להשאיר את המוצר להמשך?';label.querySelector('.simple-help')?.remove();label.insertAdjacentHTML('beforeend','<small class="simple-help">הבחירה משקפת את החשיבות של שמירת פטור או דחיית מס עתידית. היא משפיעה על סדר המשיכה, ולא על סכום המס עצמו.</small>')});const reset=$('#resetTaxBtn');reset.onclick=()=>{if(confirm('להחזיר את כל הנחות המס, האינפלציה והתאמות המוצרים לברירות המחדל?')){settings=clone(PRODUCT_TYPES);state.expectedInflation=2.5;state.products.forEach(p=>{p.annualReturn=.07;p.years=10;p.cpiAdjustment=0;p.taxNowOverride='';p.taxFutureOverride='';p.wrapperOverride='';p.taxBasisOverride=''});$('#expectedInflation').value='2.5';save();renderAdvanced();toast('כל ההגדרות שוחזרו')}}};

const luxuryResults=renderResults;
renderResults=function(){luxuryResults();$$('.loan-note').forEach(n=>n.textContent='כדאי לשקול הלוואה כנגד הקרן: הכסף נשאר מושקע, ולעיתים ניתן לקבל ריבית אטרקטיבית. יש לבדוק תנאים וסיכון.')};

document.querySelector('footer').insertAdjacentHTML('afterbegin','<div class="contact-footer"><strong>רועי רומנו · מתכנן פיננסי</strong><a href="tel:0528089808">052-8089808</a><a href="mailto:roeir@ar-fo.co.il">roeir@ar-fo.co.il</a></div>');
const headerAdvanced=renderAdvanced;renderAdvanced=function(){headerAdvanced();const heads=$$('.type-settings thead th');if(heads[4])heads[4].textContent='שמירת הטבת מס (%)'};
document.querySelector('[data-screen="1"] [data-next]').onclick=()=>go(2);
renderProducts();
