const originalMake=make;make=function(type='',value=0,cost=0){return originalMake(type,value,cost)};
const originalTypeOptions=typeOptions;typeOptions=function(selected){return`<option value="" ${!selected?'selected':''} disabled>בחרו סוג תכנית</option>`+originalTypeOptions(selected)};
if(state.products.length===1&&state.products[0].value===0&&state.products[0].cost===0)state.products[0].type='';
const brand=document.querySelector('.brand');if(!brand.querySelector('.dw-mark'))brand.insertAdjacentHTML('afterbegin','<span class="dw-mark" aria-hidden="true">DW</span>');
const netInput=$('#requiredNet');netInput.value=state.requiredNet?formatInput(state.requiredNet):'';netInput.placeholder='הכנס סכום';netInput.autocomplete='off';setTimeout(()=>netInput.focus(),50);
document.querySelector('.steps [data-go="2"] span').textContent='התכניות';
document.querySelector('[data-screen="2"] h1').textContent='אילו תכניות עומדות לרשותך?';
document.querySelector('[data-screen="2"] .screen-head p').textContent='בחרו סוג תכנית, הזינו שווי ועלות, והוסיפו תכניות לפי הצורך.';
document.querySelector('#addProductBtn').textContent='＋ הוספת תכנית';
document.querySelector('.result-panel thead th:nth-child(2)').textContent='סוג תכנית';

const revisionProducts=renderProducts;
renderProducts=function(){revisionProducts();const root=$('#products'),p=state.products[productStep],ledger=root.querySelector('.product-ledger'),total=state.products.reduce((s,x)=>s+finiteNonNegative(x.value),0);ledger.querySelector('h3').textContent='התכניות שהוזנו';ledger.insertAdjacentHTML('beforeend',`<div class="product-ledger-total"><span>שווי כולל</span><b>${fmt(total)}</b></div>`);const prev=$('#prevProduct'),next=$('#nextProduct'),plan=$('#showPlanNow');prev.textContent=productStep===0?'חזור':'→ התכנית הקודמת';prev.disabled=false;prev.onclick=()=>{if(productStep===0)go(1);else{productStep--;renderProducts()}};next.textContent=productStep<state.products.length-1?'התכנית הבאה ←':'＋ הוספת תכנית';plan.textContent='הצגת תכנית המשיכה';const type=root.querySelector('[data-k="type"]');if(!p.type){root.querySelector('.product-card').classList.add('awaiting-type')}type.onchange=e=>{p.type=e.target.value;if(settings[p.type]?.noCost)p.cost=p.value;save();renderProducts()};root.querySelector('[data-remove]')?.setAttribute('aria-label','מחיקת תכנית')};

let disclaimerAccepted=false;const directGo=go;
go=function(n){if(n===3&&screen===2){const missing=state.products.findIndex(p=>!p.type||finiteNonNegative(p.value)<=0);if(missing>=0){productStep=missing;renderProducts();toast('יש לבחור סוג תכנית ולהזין שווי נוכחי');return}if(!disclaimerAccepted){showDisclaimer();return}}directGo(n)};
document.body.insertAdjacentHTML('beforeend',`<div class="modal disclaimer-modal" id="disclaimerModal" role="dialog" aria-modal="true" aria-labelledby="disclaimerTitle"><div class="modal-card"><div class="loading-ring"></div><h2 id="disclaimerTitle">מכינים את תכנית המשיכה...</h2><p class="loading-label">מחשבים את המס והחלוקה בין התכניות</p><div class="disclaimer-copy"><h3>לפני הצגת התוצאה</h3><p>המחשבון הוא כלי סימולציה כללי להשוואת חלופות בלבד. הוא אינו מהווה ייעוץ מס, ייעוץ השקעות, ייעוץ פנסיוני, שיווק פנסיוני או המלצה לביצוע פעולה.</p><p>החישוב עשוי שלא לכלול נתוני מדד מדויקים, תקרות פטור, כספים שאינם נזילים, קצבה מזכה, הפקדות מעל תקרה, קיזוז הפסדים, הטבות אישיות ותנאים של הגוף המנהל. יש לבדוק את הנתונים עם מתכנן פיננסי ובעל מקצוע מוסמך לפני פעולה.</p><label class="consent-row"><input id="disclaimerConsent" type="checkbox"><span>קראתי והבנתי שמדובר בסימולציה כללית ולא בייעוץ או תחליף לייעוץ אישי.</span></label><button id="acceptDisclaimer" class="cta" disabled>הבנתי — הצגת התכנית</button></div></div></div><div class="modal" id="leadModal" role="dialog" aria-modal="true" aria-labelledby="leadTitle"><div class="modal-card"><button class="close" type="button">סגירה</button><h2 id="leadTitle">שליחת התכנית לרועי</h2><p>הפרטים יתווספו להודעת הדוא״ל. ההודעה תישלח רק לאחר שתאשרו אותה בתוכנת הדוא״ל שלכם.</p><form class="modal-form" id="leadForm"><label>שם מלא<input id="leadName" type="text" autocomplete="name" required></label><label>טלפון<input id="leadPhone" type="tel" autocomplete="tel" inputmode="tel" required></label><label class="consent-row"><input id="leadConsent" type="checkbox" required><span>אני מאשר/ת להעביר את הפרטים ואת סיכום התכנית לרועי רומנו לצורך יצירת קשר ומעבר על התכנית. מסירת הפרטים היא מרצון.</span></label><div class="form-error" id="leadError"></div><button class="cta" type="submit">פתיחת הודעת הדוא״ל</button></form></div></div>`);
function showDisclaimer(){const modal=$('#disclaimerModal'),copy=modal.querySelector('.disclaimer-copy');modal.classList.add('open');modal.querySelector('.loading-ring').style.display='block';modal.querySelector('.loading-label').style.display='block';copy.classList.remove('ready');setTimeout(()=>{modal.querySelector('.loading-ring').style.display='none';modal.querySelector('.loading-label').style.display='none';copy.classList.add('ready');$('#disclaimerConsent').focus()},850)}
$('#disclaimerConsent').onchange=e=>$('#acceptDisclaimer').disabled=!e.target.checked;$('#acceptDisclaimer').onclick=()=>{disclaimerAccepted=true;$('#disclaimerModal').classList.remove('open');directGo(3)};
const revisionResults=renderResults;
renderResults=function(){revisionResults();$$('.loan-note').forEach(n=>{const small=n.parentElement.querySelector('small');if(small){small.append(' '+n.textContent);n.remove()}});const email=$('#emailPlan');if(email)email.onclick=()=>{$('#leadModal').classList.add('open');$('#leadName').focus()};$('#leadModal .close').onclick=()=>$('#leadModal').classList.remove('open')};
$('#leadForm').onsubmit=e=>{e.preventDefault();const name=$('#leadName').value.trim(),phone=$('#leadPhone').value.trim();if(!name||!phone||!$('#leadConsent').checked){$('#leadError').textContent='יש למלא שם וטלפון ולאשר את העברת המידע.';return}const body=`שם: ${name}\nטלפון: ${phone}\n\n${summary()}\n\nהלקוח אישר העברת מידע ויצירת קשר.`;location.href=`mailto:roeir@ar-fo.co.il?subject=${encodeURIComponent('תכנית משיכה לבדיקה')}&body=${encodeURIComponent(body)}`};
renderProducts();
